export { default as VidyarthiLogo } from './VidyarthiLogo.png';
export { default as LoginBanner } from './loginBanner.png';
export { default as FacebookLogo } from './Facebook.png';
export { default as Register } from './register.png';
export { default as GoogleLogo } from './google.png';
export { default as OvalOne } from './Oval.png';
export { default as OvalTwo } from './Oval (1).png';
export { default as OvalThree } from './Oval (2).png';
export { default as OvalFour } from './Oval (3).png';
export { default as defaultImage } from './defaultImage.png';
export { default as Profile } from './profile.png';
export { default as Fire } from './fire.png';
export { default as Tick } from './tick.png';
export { default as Certificate } from './certificate.png';
export { default as Video } from './video.png';
export { default as LoveToLearn } from './lovetolearn.png';
export { default as Phone } from './phone.png';
export { default as Avatar } from './avatar.png';
export { default as Crown } from './crown.png';
export { default as JoinUS } from './joinus.png';
export { default as VidyarthiWhiteLogo } from './VidyarthifooterLogo.png';
export { default as BgCourse } from './bg-course.png';
export { default as NotFoundImage } from './404.png';
export { default as HomePageCourse } from './homePageCourse.png';
