export { default as VidyarthiLogo } from './VidyarthiLogo.png';
export { default as LoginBanner } from './loginBanner.png';
export { default as FacebookLogo } from './Facebook.png';
export { default as Register } from './register.png';
export { default as GoogleLogo } from './google.png';
export { default as OvalOne } from './Oval.png';
export { default as OvalTwo } from './Oval (1).png';
export { default as OvalThree } from './Oval (2).png';
export { default as OvalFour } from './Oval (3).png';
export { default as defaultImage } from './defaultImage.png';
export { default as Profile } from './profile.png';
