export const courseConstant = {
  COURSE_FETCH_REQUSET: 'COURSE_FETCH_REQUSET',
  COURSE_FETCH_SUCCESS: 'COURSE_FETCH_SUCCESS',
  COURSE_FETCH_FAILED: 'COURSE_FETCH_FAILED',
  COURSE_ADD_REQUSET: 'COURSE_ADD_REQUSET',
  COURSE_ADD_SUCCESS: 'COURSE_ADD_SUCCESS',
  COURSE_ADD_FAILED: 'COURSE_ADD_FAILED',
  COURSE_UPDATE_PAGINATION_ARGS: 'COURSE_UPDATE_PAGINATION_ARGS',
  COURSE_SET_LOADING: 'COURSE_SET_LOADING',
  COURSE_SELECTED_COURSE: 'COURSE_SELECTED_COURSE',
};

// export const LogoutConstant = 'LOGOUT__SUCCESS';
